schemaVersion: 2.3.0
metadata:
    name: aib-devspaces
    tags:
        - Jumpstarter
        - Automotive
    language: C
projects:
    - name: aib-devspaces
      git:
          remotes:
              origin: https://github.com/rh-sdv-cloud-incubator/aib-devspaces-remote.git
components:
    - name: runtime
      container:
          image: quay.io/rh-sdv-cloud/aib-base-dev:latest
          mountSources: true
          args: ["tail", "-f", "/dev/null"]
          env:
              - name: KUBEDOCK_ENABLED
                value: "true"
              - name: KUBECONFIG
                value: "/home/user/.kube/config"
              - name: JMP_CLIENT_CONFIG_HOME
                value: "/home/user/.jumpstarter"

commands:
    - id: build-container
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-container
          workingDir: ${PROJECT_SOURCE}

    - id: build-app
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-app
          workingDir: ${PROJECT_SOURCE}

    - id: clean
      exec:
          component: runtime
          commandLine: make -f Makefile.dev clean
          workingDir: ${PROJECT_SOURCE}

    - id: set-app-image
      exec:
          component: runtime
          commandLine: make -f Makefile.dev set-app-image
          workingDir: ${PROJECT_SOURCE}

    - id: build-image-ti
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-image-ti
          workingDir: ${PROJECT_SOURCE}

    - id: flash-image
      exec:
          component: runtime
          commandLine: make -f Makefile.dev flash-image
          workingDir: ${PROJECT_SOURCE}

    - id: test-sample-apps
      exec:
          component: runtime
          commandLine: make -f Makefile.dev test-sample-apps
          workingDir: ${PROJECT_SOURCE}

    - id: publish-image-reg
      exec:
          component: runtime
          commandLine: make -f Makefile.dev publish-image-reg
          workingDir: ${PROJECT_SOURCE}

    - id: deploy-changes
      exec:
          component: runtime
          commandLine: make -f Makefile.dev deploy-changes
          workingDir: ${PROJECT_SOURCE}
          group:
              kind: run
              isDefault: false

    - id: build-all
      exec:
          component: runtime
          commandLine: make -f Makefile.dev build-all
          workingDir: ${PROJECT_SOURCE}
          group:
              kind: build
              isDefault: true
